services:

  postgresdb:
    image: postgres:latest
    container_name: auth-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authadmin
      POSTGRES_PASSWORD: authadminpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - otp-net

  redisdb:
    image: redis:latest
    container_name: auth-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - otp-net

  authservice:
    build: .
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
      - redisdb
    environment:
      PORT: 8080
      DB_HOST: postgresdb
      DB_PORT: 5432
      DB_USER: authadmin
      DB_PASSWORD: authadminpass
      DB_NAME: authdb
      REDIS_ADDR: redisdb:6379
      REDIS_PASSWORD:
      JWT_SECRET: supersecretjwtkey
    networks:
      - otp-net

volumes:
  pgdata:

networks:
  otp-net:
    driver: bridge
